### PR TITLE
Fix broken links in docs/README.md

### PR DESCRIPTION
**Pull request by robiiinos**
According to README.md the link should lead to the `master` blob. But in the /docs/ folder, the README.md links lead to an old and unreachable URL (404; in blob `dd56e02` in of `master`).

This PR fix this.
Thanks for your time and the library 💯

### CODE REVIEW

**Comment by robiiinos** [comment]
If you plan on merging this PR, please advice me on how I could fix the failed CI test... Thanks

**Comment by s1na** [comment]
Hey @robiiinos, thanks for the PR!

Those docs are auto-generated via `npm run docs:build`. Even if we fix them manually now, the next time they're generated the fix will be overwritten. It seems the links are anchored to a specific commit, I'm not sure why!

Btw, regarding the CI failure, we're experiencing a problem with coveralls since 2 days, hopefully it's resolved soon.

**Comment by s1na** [comment]
Update: I think the reason the links are not working is that the commit history has been modified after the docs were generated (e.g. via `rebase`).

**Comment by robiiinos** [comment]
Update : I found on we can get this done without having to build the docs at each commit; I'm closing this PR to open a new one that will fix this definitely.

Thanks for pointing the way !

**Pull request closed without merging**
