### PR TITLE
es6 round 1 - remove all vars and anon functions

### PR DESCRIPTION
**Pull request by Silur**
nothin special here

### CODE REVIEW

**Comment by wanderer** [comment]
looks good to me. @kumavis do you think this would break anything downstream for ya?

**Comment by kumavis** [comment]
Js-ipfs wants node v4 support (not sure if we currently have that)

I love es7, but here it's providing minimal benefit and yet reduces platform compatibility, so I'm leaning against merging this atm.

I wish there was an elegant way to transpile and publish 

Thanks for the PR, let me think about it

**Comment by kumavis** [comment]
Talked to ipfs, they have abandoned node v4 support so we're good to merge on this

**Comment by wanderer** [comment]
after discussion we decided to merge

**Pull request merged**
