### PR TITLE
New release v7.0.5

### PR DESCRIPTION
**Pull request by holgerd77**

### CODE REVIEW

**Review by ryanio — APPROVED** [review]
lgtm!

**Comment by holgerd77** [comment]
Just published as [v7.0.5](https://github.com/ethereumjs/ethereumjs-util/releases/tag/v7.0.5) on npm.

**Comment by evertonfraga** [comment]
I got late to the party, but given this update had feature additions, according to the semver bible, it should probably be represented as 7.1.0.

**Comment by holgerd77** [comment]
This is now published on npm, I wouldn't want to go through the hazzle and re-publish or something for this release any more, but we can discuss how we want to handle this case in the future.

Will continue discussion on Discord.

**Pull request merged**
