### PR TITLE
New release v6.2.0

### PR DESCRIPTION
**Pull request by holgerd77**

### CODE REVIEW

**Comment by holgerd77** [comment]
Hmm, the `travis-ci/push` build went through but wasn't reported for some reason. 🤔 Have re-triggered.

**Comment by holgerd77** [comment]
Ah ok, this is working now. Ready for review.

**Comment by alcuadrado** [comment]
Thanks for preparing this @holgerd77! This release has a few changes that will make the library much better.

I think this is missing from the changelog: https://github.com/ethereumjs/ethereumjs-util/pull/168

Or is it not included in the release? IMO it's pretty important to release that upgrade soon, as it's breaking things like web3 (see: https://github.com/ethereum/web3.js/issues/3181 )

**Comment by evertonfraga** [comment]
It is included, as shown on [master](https://github.com/ethereumjs/ethereumjs-util/blob/master/package.json#L95).

I'm sending a commit adding it to the changelog.

**Comment by holgerd77** [comment]
@alcuadrado Phew, the PR which actually triggered this release, hmm, thanks @evertonfraga for adding. Will now merge and release.

**Comment by holgerd77** [comment]
Released this as [v6.2.0](https://github.com/ethereumjs/ethereumjs-util/releases/tag/v6.2.0) on npm.

**Pull request merged**
