### PR TITLE
Support BN.isBN in toBuffer()

### PR DESCRIPTION
**Pull request by axic**
WIP - needs tests first.

### CODE REVIEW

**Comment by axic** [comment]
I'm not sure what to do with this. Essentially we should remove the `toArray` case because `isBN` supersedes it.

**Comment by axic** [comment]
@holgerd77 I think this should be merged after the release

**Comment by holgerd77** [comment]
@axic Ok

**Comment by holgerd77** [comment]
@axic Can you rebase? This is coming from you repo!

**Comment by axic** [comment]
Rebased.

**Pull request merged**
