### PR TITLE
Make v an int in ecrecover()

### PR DESCRIPTION
**Pull request by axic**
This is a breaking change. It would be nice to have it merged in the future.

### CODE REVIEW

**Comment by wanderer** [comment]
the reason it is this way is because the signuatures in ethereumjs-tx and and ethereumjs-vm are always a buffer. And it make the API more simple and unified

**Comment by axic** [comment]
Is `v` only a Buffer in ethereumjs-tx because of the mess of RLP?

**Comment by wanderer** [comment]
yeah, there is no types in RLP. so everything always comes out a buffer

**Comment by wanderer** [comment]
ok incoming breaking change

**Pull request merged**
