### PR TITLE
do not allow 0X in address

### PR DESCRIPTION
**Pull request by tranvictor**

### CODE REVIEW

**Comment by tranvictor** [comment]
refer to #89

**Comment by axic** [comment]
@wanderer @kumavis @fanatid any comments?

**Comment by kumavis** [comment]
just clarifying - with this PR: `0xabcd...` is ok but `0Xabcd` is not, correct?

**Comment by tranvictor** [comment]
@kumavis it is correct and it is also consistent to `defineProperties` that way.

**Comment by axic** [comment]
@kumavis good to go?

**Pull request merged**
