### PR TITLE
New Release v7.0.8

### PR DESCRIPTION
**Pull request by holgerd77**
//cc @spalladino

### CODE REVIEW

**Comment by spalladino** [comment]
That was fast, thanks @holgerd77!

**Review by cgewecke — APPROVED** [review]
LGTM!

**Review by ryanio — APPROVED** [review]
also lgtm!

**Comment by holgerd77** [comment]
Just release this as [v7.0.8](https://github.com/ethereumjs/ethereumjs-util/releases/tag/v7.0.8) on npm.

**Pull request merged**
