### PR TITLE
Introduce toMessageSig() and fromMessageSig()

### LINKED ISSUE #36: Serialize message signatures
they come out in this format:
```js
function concatSig(v, r, s) {
  r = ethUtil.fromSigned(r)
  s = ethUtil.fromSigned(s)
  v = ethUtil.bufferToInt(v)
  r = ethUtil.toUnsigned(r).toString('hex')
  s = ethUtil.toUnsigned(s).toString('hex')
  v = ethUtil.stripHexPrefix(ethUtil.intToHex(v))
  return ethUtil.addHexPrefix(r.concat(s, v).toString("hex"))
}
```

### PR DESCRIPTION
**Pull request by axic**
Do not merge yet.

Checking if this makes sense, cc @wanderer @kumavis

Fixes #36

### CODE REVIEW

**Comment by wanderer** [comment]
Are this function being used somewhere else?

**Comment by axic** [comment]
helpeth, testrpc (for eth_sign), I think @kumavis uses it for something?

It is getting some usage since it became easier to validate within a contract a few weeks back (see  https://gist.github.com/axic/5b33912c6f61ae6fd96d6c4a47afde6d).

**Comment by wanderer** [comment]
usecase look good to me. Maybe change the name to `from/toRPCSig`?

**Comment by kumavis** [comment]
@axic can you add a test? plz

**Pull request merged**
