### PR TITLE
Fixed signature to comply to Geth and Parity (see #131);

### PR DESCRIPTION
**Pull request by Neurone**
Some formatting;

### CODE REVIEW

**Comment by fanatid** [comment]
Right now totally unclear what was changed, please do not change code style.

**Comment by Neurone** [comment]
Sorry, I prepare another branch containing only fixed code.

**Comment by fanatid** [comment]
No need hundreds branches with hundreds Pull Requests, just made force push.

**Comment by Neurone** [comment]
Ok, done.

**Pull request closed without merging**
