### PR TITLE
Implement isValidSignature()

### PR DESCRIPTION
**Pull request by axic**
No tests yet, WIP.

### CODE REVIEW

**Comment by axic** [comment]
@wanderer should `ecrecover()` have a `homestead` flag too?

**Comment by wanderer** [comment]
@axic ecover should actually be ok, If someone can find a tx that that has high r values in the chain then we will have to add it, but I don't think that is case.

**Comment by fanatid** [comment]
`isVlidSignature` is not the best name, maybe `isValidSignatureNumbers`?

**Comment by axic** [comment]
@fanatid I agree. Would `isValidSignatureParameters` work?

**Comment by fanatid** [comment]
@axic  I don't know, anything except `isValidSignature` :smile:

**Pull request merged**
