### PR TITLE
Fix broken tests

### PR DESCRIPTION
**Pull request by vanesyan**
This PR fixes all broken tests that are left in `update-secp2561-depdency`. And is complementary to #228.

### CODE REVIEW

**Comment by vanesyan** [comment]
Can someone check tests, they are failing because of `ethereumjs-config-lint`. However `ethereumjs-config-lint` was broken for me too and locally I was running `test:node` instead of `test`.

**Comment by ryanio** [comment]
@vanesyan have you tried `npm run lint:fix` and committing any fixed files?

**Comment by cgewecke** [comment]
@vanesyan Thanks so much for this!

Have taken these changes and added them to #228 in e2a389c, preserving you as the author.

Closing here.

**Comment by vanesyan** [comment]
NP, thanks!

**Pull request closed without merging**
