### PR TITLE
Split off secp256k1 into its own file [WIP]

### LINKED ISSUE #35: Split off the crypto functions
See https://github.com/ethereumjs/ethereumjs-util/pull/34#issuecomment-211394212

### PR DESCRIPTION
**Pull request by axic**
Fixes #35.

Dont merge yet - not fully happy with it.

### CODE REVIEW

**Comment by fanatid** [comment]
@axic you also can moved out address and hash functions

**Comment by axic** [comment]
Will rebase this after #121 is merged.

**Comment by holgerd77** [comment]
@axic I have the general idea to have a ``v6.0.0`` release after this ``V`` ``27``/``28`` PR https://github.com/ethereumjs/ethereumjs-util/issues/131 is settled and also to remove the ``SHA3`` aliases there.

Would be nice to have the changes from this PR integrated as well, is this somewhat settled and could you rebase after the changes from above get merged?

**Comment by holgerd77** [comment]
There was also the idea to spit off the constants into its own file https://github.com/ethereumjs/ethereumjs-util/issues/122, maybe this would fit here as well if it is generally regarded as a good idea.

**Comment by s1na** [comment]
Superseded by #182.

**Pull request closed without merging**
